name: Linters

on: [push]

jobs:
  test-and-lint:
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        python-version: [ "3.10" ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Check code typos
        uses: crate-ci/typos@master
        with:
          files: ./slam ./examples
          config: _typos.toml

      - name: Check imports
        uses: isort/isort-action@master
        with:
          configuration: "--settings-file=.isort.cfg --profile=black"

      - name: Run flake8
        uses: py-actions/flake8@v2

      - name: Run black
        uses: psf/black@stable
        with:
          options: "--check --verbose --diff --extend-exclude '__init__.py'"
          version: "22.8.0"
